### ISSUE TITLE
Save custem preset

### ISSUE THREAD

**Issue by cenobitedk** [ejci/Chrome-Audio-EQ#14]
I use this extension to compensate for the frequency response of my headphones. I know this could be done system wise, but has proved to be a little troublesome and this extension is much easier to work with. :-)
It would be cool though to be able to save my custom settings as a new preset.

**Comment by victorel-petrovich** [comment]
+1 !!! I love it this enhancement too. I use the extension because of my hearing deficit in higher frequencies, so that would help me.

**Comment by ejci** [comment]
Done
