### ISSUE TITLE
Audible click upon waking Chromebook, about 1-second interval

### ISSUE THREAD

**Issue by AlienMindTrick** [ejci/Chrome-Audio-EQ#16]
When I close my Acer C710 Chromebook (16GB SSD) and then reopen it, or when it wakes from its own self-induced sleep mode, any audio playing will have an audible background click or pop that occurs at about 1-second intervals. After disabling Extensions in Chrome one at a time, I narrowed it down to Audio EQ. 

When the click begins, and it always does upon waking Chrome when audio is playing, I can disable Audio EQ, re-enable it, and the click goes away. I just discovered that hack today. Prior to this, I had to restart my Chromebook to make the click stop.

Hopefully that indicates how much I like Audio EQ, too. Although, to be fair, I didn't find the source of the click until today. It's certainly not a deal breaker, but it is very noticeable once you notice it the first time. 

The thing is that the click isn't consistent, or at least doesn't sound like it. It varies in volume, and at times, even in quiet passages in the music, can't be heard. It IS a background sound and has to be listened for, but again, once you hear it, you'll always notice it. 

Nonetheless, Audio EQ is a wonderful extension! Thank you. :)

**Comment by voodoojello** [comment]
I'm noticing a similar issue on my Pixel (41.0.2272.76 - 6680.58.0 - Google_Link.2695.1.155). Audible clicks and pops during HTML5 playback. Disabling Audio EQ and reloading Chrome seems to make it stop.
