### ISSUE TITLE
Audible noise when closing tabs

### ISSUE THREAD

**Issue by jessejoe** [ejci/Chrome-Audio-EQ#18]
I'm using the EQ for listening to Google Play Music, and it works great. However frequently when closing a tab, there will be an audible scratch/break in sound. I've uninstalled/reinstalled the extension multiple times to confirm it's definitely the extension and not Google Play Music. It doesn't occur when the extension is not installed. I'm using a basically new MBP, so I don't think it's a resources issue. Let me know if there's anything I can do to help debug.

**Comment by jessejoe** [comment]
Just FYI this fix still doesn't appear to have made it to the web store.

**Comment by jessehudl** [comment]
Also, just FYI this issue does still occur occasionally. It's not as bad as before, but for instance this URL will still cause it - https://support.pagerduty.com/hc/en-us/articles/203565440-Using-Override-System-Volume-on-Android-L-Lollipop-5-0

**Comment by ejci** [comment]
I will look into it. And hopefully finish the new version this weekend

**Comment by l3db3tt3r** [comment]
I have this Issue as well, scratch sound, differs in tone and briefness of length:
Audio EQ 0.3.1.2
Chrome 40.0.2214.111 (64-bit)

I am unable to reproduce it reliably. It seems to happen more when I have a tab open for a bit of time.

**Comment by vkammerer** [comment]
Same here, each time i close a tab in the window running my player, I hear a  "crash sound"

**Comment by jessehudl** [comment]
It also seems like the patch here isn't applied to the version in the Chrome Web Store, and the version of the extension in git (0.3.1.1) also isn't the same as the version in the Chrome Web Store (0.3.1.2). This patch seems to at least make it better but doesn't seem to be in the official version.

Is there a way to get the latest extension with the new features and apply this patch?

**Comment by l3db3tt3r** [comment]
Update:
I haven't had this issue since upgrading Chrome:
44.0.2377.0 canary (64-bit)
