### ISSUE TITLE
Not working on Ubuntu using chromium

### ISSUE THREAD

**Issue by adevecs** [ejci/Chrome-Audio-EQ#19]
Forced videos to load in html5 with magic actions for youtube extension equalizer has never worked, works on mac great

**Comment by ejci** [comment]
Did you tried HTML5ify to force html5 for youtube?
https://chrome.google.com/webstore/detail/html5ify/jikbjpjgjmmdhcmlagappehlpiljoaop

**Comment by madococa** [comment]
I’ll try it now 






Sent from Windows Mail





From: Miroslav Magda
Sent: ‎Thursday‎, ‎January‎ ‎8‎, ‎2015 ‎10‎:‎27‎ ‎AM
To: ejci/Chrome-Audio-EQ





Did you tried HTML5ify to force html5 for youtube?
https://chrome.google.com/webstore/detail/html5ify/jikbjpjgjmmdhcmlagappehlpiljoaop
