### ISSUE TITLE
After some usage it makes Youtube embedded html5 videos unable to play 

### ISSUE THREAD

**Issue by vhanla** [ejci/Chrome-Audio-EQ#20]
It works nice, but it has some drawbacks after a while (it works on other sites randomly), specially while trying to play youtube videos which are embedded in non youtube pages, if you click play, it will start buffering (loading) the video but it won't play even after dragging to another position it doesn't answer and the video won't play anymore, even after that, opening the video in youtube page it won't play until you restart chrome or disable this extension.

Tested on Windows 8.1 and Chrome 39 64bits. 

Notice: I've seen this issue only with youtube videos, other html5 videos seems unaffected.

It would be great to add a blacklist for pages, so it won't apply the sound equalizer on every page you visit.

**Comment by ejci** [comment]
I will try look into it

**Comment by ejci** [comment]
I wasnt able to reproduce it...
