### ISSUE TITLE
No longer works with Google Play Music

### ISSUE THREAD

**Issue by mason0** [ejci/Chrome-Audio-EQ#25]
This has recently stopped working when streaming via Google Play Music. HTML5 audio is enabled in the Labs settings of Play Music, and the extension still works with other sources of HTML5 audio such as Youtube.

**Comment by Frisch12** [comment]
I have the same issue. Here is some more information: 
In WebConsole error occures: Uncaught SyntaxError: Failed to construct 'AudioContext': number of hardware contexts reached maximum (6). occures

Furthermore webkitAudioContext is deprecreated, better use AudioContext (suggestion of Google Chrome)

**Comment by ejci** [comment]
Bug is fixed but version was not shipped yet...
