### ISSUE TITLE
Chrome-Audio-EQ disables microphone and speakers on Video Google Hangouts

### ISSUE THREAD

**Issue by tmitchmd** [ejci/Chrome-Audio-EQ#27]
The above says it all. Had to disable the extension to use hangouts on this chromebook.

**Comment by ejci** [comment]
Will fix it ASAP. Sorry for that

**Comment by tmitchmd** [comment]
I use the new Chromebook Pixel btw.

**Comment by ejci** [comment]
Should work with 0.3.2.x
