### ISSUE TITLE
Google Play Music not working

### ISSUE THREAD

**Issue by lascolaco** [ejci/Chrome-Audio-EQ#30]
Hello there,

Is there any issues with the equalizer when using Google Play Music?

The extension works just fine with Youtube for example, but with Google Play Music after forcing HTML5 it doesn't work.

Thank you

**Comment by ejci** [comment]
Are you using also Google music extension? Because if they are both enabled EQ will not work.

**Comment by lascolaco** [comment]
I was and was causing the conflict, as soon  I have removed the extension it worked straight away!

Thank you for the help!
