### ISSUE TITLE
Audio EQ does not work on any site other than Youtube.

### ISSUE THREAD

**Issue by reizeprimus** [ejci/Chrome-Audio-EQ#32]
So far other than Youtube, all other sites that stream videos in HTML5 will have the sound disabled/muted as long as Audio EQ is enabled or installed.

Only Flash sounds work while Audio EQ is enabled.

**Comment by ejci** [comment]
Thank for reporting. I have a fix for that. But my fix is causing another issues so I need to fix that before I will release new version :(

**Comment by ejci** [comment]
I published version 0.3.2.0 with fix. Can you please let me know if you still have issues?

**Comment by reizeprimus** [comment]
Hi, it still doesn't work for me other than Youtube. A site I use is Kissanime.com, you can use that as a reference for whether the patches work or not as they stream shows in HTML5.

**Comment by ejci** [comment]
Can you pls share a link on Kissanime.com that is not working?

**Comment by reizeprimus** [comment]
Hi its pretty much all the html5 on the site, but you can use this.

http://kissanime.com/Anime/Pokemon-XY/Episode-064?id=96682

I'm not proud of it, but it also doesn't work for other "adult-oriented entertainment" with HTML5 that i shall not name.

**Comment by ejci** [comment]
You can disable audio on that site so it will not block your sound. Check here https://github.com/ejci/Chrome-Audio-EQ/issues/37

The reason why its not working is that the media files (HTML5) are streamed from google video domain that is not returning headers (allow-same-origin). There is security restriction in Chrome (in HTML specification) that is not allowing to manipulate video/audio streamed from different domain if those headers are not set (thats why the video is muted).

**Comment by reizeprimus** [comment]
Oh okay thanks. Hopefully there will be a workaround for this security thing in the future.
