### ISSUE TITLE
Pocket Casts streaming no audio when EQ Extension enabled

### ISSUE THREAD

**Issue by twiceover** [ejci/Chrome-Audio-EQ#37]
No audio in Pocketcasts.com web player when this extension is enabled.

**Comment by ejci** [comment]
I published new version (0.3.2.0). You should get the update in an hour or so.
Can you please test it on pocketcasts.com (I don't have account there) and let me know if its working or not?

**Comment by twiceover** [comment]
This actually made things worse for PocketCasts' player.  In the previous version, the player would play the episode but without audio.  Now playback fails:
![image](https://cloud.githubusercontent.com/assets/13166880/8640737/d65268d2-28c8-11e5-86e3-49f306f27dca.png)

**Comment by ejci** [comment]
You can disable EQ per page. Just "right click" on the PocketCasts page and disable EQ.
<img width="513" alt="screen shot 2015-07-13 at 09 34 47" src="https://cloud.githubusercontent.com/assets/1025656/8644903/20e82eca-2943-11e5-916e-57de2d1949e4.png">
This will disable EQ from the page.
Let me know if it works pls.

**Comment by twiceover** [comment]
Yes, that worked.  Thank you!
