### ISSUE TITLE
Audio request cookies are not sent

### ISSUE THREAD

**Issue by DenisDorokhov** [ejci/Chrome-Audio-EQ#39]
After the last update (13th of July I believe) I've found that cookies are not sent anymore when requesting HTML5 audio. I've found that Audio EQ is the reason after enabling / disabling extensions installed on my machine. Are anybody else experiencing the same problem?

**Comment by ejci** [comment]
Hi can you pls elaborate? 

Because the reason why its not sending cookies can be that when Im attaching audioContext to video element Im also adding crossorigin ="anonymous" to the video tag.

Can you check if its indeed caused by that?

**Comment by DenisDorokhov** [comment]
Hi ejci,

Unfortunately I don't have experience in debugging Google Chrome extensions and I don't have much time right now to dig deeper into this... But what I could give you is the link to web site where I'm experiencing this (this is a demo of my open source project):

http://pony.dorokhov.net/demo
Login: foo@bar.com
Password: demo

Just sign in and try to play any audio. You will get HTTP 401 because token cookie was not sent. When I disable your extension and reload the page, audio can be played again (cookies are being sent again). If you have time, please let me know if you're able / unable to reproduce this behaviour.

**Comment by ejci** [comment]
Thanks. I think I know whats going on. I will try to fix it and release new version in the evening.

**Comment by DenisDorokhov** [comment]
Thanks for your work and fast response!

**Comment by ejci** [comment]
I released new version (v0.3.2.2) that is solving issue with your site. I tested it with the credentials you gave me and it worked. Let me know if its working also for you.

**Comment by DenisDorokhov** [comment]
Hi ejcl, it works now! Thanks!
