### ISSUE TITLE
Doesn't work on Chrome 47

### ISSUE THREAD

**Issue by thicarmo** [ejci/Chrome-Audio-EQ#45]
The eq isn't working anymore on this new chrome update. Could U fix it???

**Comment by ejci** [comment]
What OS and chrome version do you have?

**Comment by ben-page** [comment]
It appears to have stopped working for me as well. The sliders move but have no effect. Clicking on a preset does nothing, not even adjust the sliders.

I'm on Windows 10 with Chrome 47.0.2526.80.

**Comment by ejci** [comment]
Something is wrong with windows version of chrome. Mac OS X version works without any problems :/

**Comment by thicarmo** [comment]
When will you launch an update?

**Comment by ejci** [comment]
Today in the evening. Sorry for delay.

**Comment by thicarmo** [comment]
Thanks!!!!

**Comment by ejci** [comment]
Cant reproduce it with Chrome 47.0.2526.106m on Win 10 :/
This issue is really weird...

**Comment by ben-page** [comment]
@thicarmo, why did you close this? There hasn't been a update, has there?

**Comment by ben-page** [comment]
It really is weird. I just reinstalled Windows 10 (for unrelated reasons). The extension is working for me now.

**Comment by ben-page** [comment]
Oh, wait. Chrome updated Chrome 47.0.2526.106. They must has fixed whatever caused the problem.

**Comment by ejci** [comment]
@ben-page Yep it looks like it was a issue with specific version of chrome (47.0.2526.80).
