### ISSUE TITLE
presets don't work in Chrome 52

### ISSUE THREAD

**Issue by tripscripts** [ejci/Chrome-Audio-EQ#54]
the "presets" button is not working properly in the new "52" version of Chrome. there is no response when you click it. you have to control all of the settings manually now.

**Comment by elodszopos** [comment]
Please, take a look at this. @ejci

**Comment by elodszopos** [comment]
```A DOM event generated from JavaScript has triggered a default action inside the browser. This behavior is non-standard and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5718803933560832 for more details.```

Popup.js, line 163.

**Comment by ejci** [comment]
Related to #57
