### ISSUE TITLE
Preset button not working in Chrome 53

### ISSUE THREAD

**Issue by Jaxlyfe** [ejci/Chrome-Audio-EQ#57]
I updated to 53, and re-installed the audio-eq aswell, but i still have to do manual presets.

Is there a way to change the preset cache or data to a certain one, in order to loophole the bug?

**Comment by pitxels** [comment]
Same here.

**Comment by InservioLetum** [comment]
Same problem... Veeery irritating, especially since inspecting the code suggests the extension can do SOOO much more.

**Comment by ejci** [comment]
Hi sorry for late reply. I went for vacation and was trying to stay away from internet for a while. Will pick it up in next few days.

**Comment by Jaxlyfe** [comment]
Thanks dude, love this plugin to pieces

**Comment by ejci** [comment]
Fix will be live with next release (in couple of hours)

**Comment by elodszopos** [comment]
Awesome. Thank you very much for making even some of the cheapest headsets a bangin' experience when listening to music @ work. I'm sure most people can relate. Most appreciated @ejci !
