### ISSUE TITLE
Chrome: Gifs wont play anymore (example 9gag)

### ISSUE THREAD

**Issue by Nasthran** [ejci/Chrome-Audio-EQ#73]
Hey dev`s,

i just want to mention that i dont discovered any other bugs so far, but usualy i spend my spare time on sites like 9gag, if your plugin is "active" no gif wants to play anymore..

hope you guys gonna fix this! tyvm.
regards Nasthran

**Comment by ejci** [comment]
Fixed with 7d6b107
