### ISSUE TITLE
Chrome-Audio-EQ silently breaks video playback on some sites

### ISSUE THREAD

**Issue by CalebRouleau** [ejci/Chrome-Audio-EQ#74]
Hi, Chrome <video> developer here.

1. I go to https://gfycat.com/AlienatedFatBlackrussianterrier with the Chrome-Audio-EQ turned on, and the video won't play unless I right click and "Open Video in New Tab" then it opens https://fat.gfycat.com/AlienatedFatBlackrussianterrier.mp4, and that plays just fine.

2. I go to https://gfycat.com/AlienatedFatBlackrussianterrier after removing the Chrome-Audio-EQ extension and everything plays just fine.

I'm not sure why this is. It seems to happen for gif-like videos (with attributes "autoplay muted loop")

I'm on Mac OS X, running Chrome Stable version 56.0.2924.87.

**Comment by ejci** [comment]
Can't reproduce...
